# Copyright 1999-2006 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.15.0

inherit perl-module

S=${WORKDIR}/Class-Base-0.03

DESCRIPTION="No description available"
HOMEPAGE="http://search.cpan.org/search?query=Class-Base&mode=dist"
SRC_URI="mirror://cpan/authors/id/A/AB/ABW/Class-Base-0.03.tar.gz"


IUSE=""

SLOT="0"
LICENSE="|| ( Artistic GPL-2 )"
KEYWORDS="~amd64"

