#! /bin/bash

# <li>Package: Lynis</li>
# <li>Version: 2.4.8</li>
# <li>SHA1 hash: 91b7e94c1b39c4b41340c55c0ff601e04aef7387</li>
# <li>SHA256 hash: 6be0dcb0e3c66c76266944b1c5b6f1d8ba617dc1ce89b8d278f4e1f990a6f70a</li>

source /lib64/rc/sh/functions.sh

# known variables
CATEGORY=app-forensics
PN=lynis
source "${0%/*}"/common.sh
VERSION_URI=https://cisofy.com/download/lynis/

# get upstream download page, which will tell us also the version
wget -q -c -O - ${VERSION_URI} | xmllint --html - 2> /dev/null > "${HTML}"

PV="$( sed -rn -e 's|<li>Version: ([0-9.]*)</li>|\1|p' "${HTML}" )"
HASH=$( sed -rn -e 's|<li>SHA256 hash: ([0-9a-f]*)</li>|\1|p' "${HTML}" )

einfo "found version \"${PV}\""
einfo "SHA256 hash:  \"${HASH}\""

if ! check_ver ${CATEGORY} ${PN} ${PV} ; then
    A=${PN}-${PV}.tar.gz
    SRC_URI="https://cisofy.com/files/${A}"
    wget "${SRC_URI}"
    CHECK=$( sha256sum "${A}" | grep -c ^${HASH} )
    if [[ ${CHECK} == 0 ]] ; then
        error "wrong sha256sum \"${SRC_URI}\""
        exit 1
    else
        mv -i ${A} ${DISTDIR}
    fi

    LAST_VERSION="$(equery --quiet which -e ${CATEGORY}/${PN} | head -n1)"
    NEXT_VERSION="${REPO_PATH}/${CATEGORY}/${PN}/${PN}-${PV}.ebuild"
    einfo "Found new version \"${PV}\""
    einfo "Try the following commands for a preliminary test:"
    echo "cp -i \\"
    echo " ${LAST_VERSION} \\"
    echo " ${NEXT_VERSION}"
    einfo ""
    echo "ebuild ${NEXT_VERSION} manifest install clean"
else
    einfo "already there"
fi
rm -f ${HTML}
