#! /bin/bash

source /lib64/rc/sh/functions.sh

# known variables
source "${0%/*}"/common.sh
GITHUB_OWNER="PyMySQL"
GITHUB_REPO="PyMySQL"
GITHUB_TAG=$(
    curl --silent \
        "https://api.github.com/repos/${GITHUB_OWNER}/${GITHUB_REPO}/tags" \
    | jq -r '.[0].name'
)

PV=${GITHUB_TAG#v}

einfo "found version \"${PV}\""
# einfo "SHA1 hash \"${HASH}\""

if ! check_ver ${CATEGORY} ${PN} ${PV} ; then
    A=${PN}-${PV}.tar.gz
    SRC_URI="https://github.com/PyMySQL/PyMySQL/archive/v${PV}.tar.gz"

    wget -O ${A} "${SRC_URI}"
    CHECK=-1
    # CHECK=$( sha256sum "${A}" | grep -c ^${HASH} )

    if [[ ${CHECK} == 0 ]] ; then
        einfo "wrong checksum!"
        einfo "This is normal github package has different checksum than pip"
    else
        message_and_cleanup ${A}
    fi
else
    einfo "already there"
fi
rm -f ${HTML}
