#! /bin/bash

# <option value="percona-toolkit/3.0.2" selected>Percona Toolkit 3.0.2</option>

source /lib64/rc/sh/functions.sh

# known variables
source "${0%/*}"/common.sh
VERSION_URI=https://www.percona.com/downloads/percona-toolkit/

# get upstream download page, which will tell us also the version
wget -q -c -O - ${VERSION_URI} | xmllint --html - 2> /dev/null > "${HTML}"

PV="$( sed -rn -e 's|<option value="percona-toolkit/([0-9.]*)" selected>Percona Toolkit [0-9.]*</option>|\1|p' "${HTML}" )"

einfo "found version \"${PV}\""

if ! check_ver ${CATEGORY} ${PN} ${PV} ; then
    A=${PN}-${PV}.tar.gz
    SRC_URI="wget https://www.percona.com/downloads/${PN}/${PV}/source/tarball/${A}"
    wget "${SRC_URI}".md5sum
    wget "${SRC_URI}"
    md5sum -c ${A}.md5sum
    CHECK=${?}
    if [[ ${CHECK} ]] ; then
        message_and_cleanup ${A}
        rm -f ${A}.md5sum
    fi
else
    einfo "already there"
fi
rm -f ${HTML}
