#! /bin/bash

export TZ=UTC
export LANG=C
export META=${0%/*}/../metadata

D=$( date --iso-8601=ns )

date -d "${D}" > "${META}"/timestamp
date -d "${D}" +"%a, %d %b %Y %H:%M:%S %z" > "${META}"/timestamp.chk
date -d "${D}" +"%s %a %d %b %Y %I:%M:%S %p %Z" > "${META}"/timestamp.x
git show -s --format="%H %ct %cI" > "${META}"/timestamp.commit

